# version: '3.8'

services:
    pgdb:
        image: postgres:14
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - transcendance_net
        env_file:
            - .env.example
        restart: always

    backend:
        image: django:trns
        container_name: backend
        build:
            context: ./srcs/api/
        volumes:
            - ./srcs/api/:/var/www/
        networks:
            - transcendance_net
        ports:
            - 8000:8000
        depends_on:
            - pgdb
        env_file:
            - .env.example
        restart: on-failure
        # environment:
        #     DEBUG: True # ['True', 'False']
        #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        #     DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
        #     DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        #     DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}


volumes:
    postgres_data:
    backend_files:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         o: bind
    #         device: /Users/zel-bouz/transcendance/srcs/api

networks:
    transcendance_net:
