version: '3'

services:
    pgdb:
        image: postgres:14
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - transcendance_net
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    backend:
        image: backend:trns
        container_name: backend
        build:
            context: ./srcs/api/
        volumes:
            - backend_files:/var/www/
        networks:
            - transcendance_net
        ports:
            - 8000:8000
        depends_on:
            - pgdb
        environment:
            DEBUG: True # ['True', 'False']
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}


volumes:
    postgres_data:
    backend_files:

networks:
    transcendance_net: