# version: '3.8'

services:
    pgdb:
        image: postgres:14
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - transcendance_net
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}


    backend:
        image: django:trns
        container_name: backend
        build:
            context: ./srcs/api/
        volumes:
            - backend_files:/var/www/
        networks:
            - transcendance_net
        ports:
            - 8000:8000
        depends_on:
            - pgdb
        restart: on-failure
        environment:
            DEBUG: True # ['True', 'False']
            DJANGO_SETTING_MODULE: config.django.local
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgdb:5432/${POSTGRES_DB}
            DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
            DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
            DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}


volumes:
    postgres_data:
    backend_files:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         o: bind
    #         device: /Users/zel-bouz/transcendance/srcs/api

networks:
    transcendance_net:
